import type { Metadata } from "next";
import "./globals.css";
import SideBar from "@/components/common/SideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sideBarWidth = 240;

  return (
    <html lang="en">
      <SideBar sideBarWidth={sideBarWidth} />
      <body style={{ marginLeft: `${sideBarWidth}px` }}>{children}</body>
    </html>
  );
}
